name: dev-env

services:
  node:
    image: node
    entrypoint: /usr/bin/tail -f /dev/null
    volumes:
      - node:/usr/local/bin
    extends:
      service: common
      file: ./common.yaml

  dotnet:
    image: mcr.microsoft.com/dotnet/sdk
    entrypoint: /usr/bin/tail -f /dev/null
    volumes:
      - dotnet:/usr/share/dotnet
    extends:
      service: common
      file: ./common.yaml

  vscode:
    image: gitpod/openvscode-server
    working_dir: /home/${HOME}
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/dotnet:/var/node:/var/docker
    volumes:
      - vscode:/home/workspace
      - /home/${HOME}/.ssh:/home/openvscode-server/.ssh
      - /home/${HOME}:/home/${HOME}
      - dotnet:/var/dotnet
      - node:/var/node
      - docker:/var/docker
      - /var/run/docker.socket:/home/workspace/.docker/docker.socket
    extends:
      service: common
      file: ./common.yaml

  docker:
    image: docker
    volumes:
      - docker:/usr/local/bin
    extends:
      service: common
      file: ./common.yaml

volumes:
  vscode:
    name: vscode
  node:
    name: node
  dotnet:
    name: dotnet
  docker:
    name: docker
