name: dev-env

services:
  node:
    image: node
    entrypoint: /usr/bin/tail -f /dev/null
    volumes:
      - node:/usr/local/bin
      - yarn:/opt/yarn-v1.22.19
    extends:
      service: common
      file: ./common.yaml

  dotnet:
    image: mcr.microsoft.com/dotnet/sdk
    entrypoint: /usr/bin/tail -f /dev/null
    volumes:
      - dotnet:/usr/share/dotnet
    extends:
      service: common
      file: ./common.yaml

  powershell:
    image: mcr.microsoft.com/powershell
    entrypoint: /usr/bin/tail -f /dev/null
    volumes:
      - pwsh:/opt/microsoft/powershell/7
      - libicu:/usr/lib/x86_64-linux-gnu
    extends:
      service: common
      file: ./common.yaml

  docker:
    image: docker
    privileged: true
    volumes:
      - docker:/usr/local/bin
    extends:
      service: common
      file: ./common.yaml

  vscode:
    image: gitpod/openvscode-server
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/dotnet:/var/yarn/bin:/var/node:/var/pwsh:/var/docker
    volumes:
      - vscode:/home/workspace
      - /home/${USERNAME}/.ssh:/home/openvscode-server/.ssh:ro
      - /home/${USERNAME}:/home/${USERNAME}
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dotnet:/var/dotnet:ro
      - docker:/var/docker:ro
      - node:/var/node:ro
      - pwsh:/var/pwsh:ro
      - yarn:/var/yarn:ro
      - libicu:/usr/lib/x86_64-linux-gnu:ro
    extends:
      service: common
      file: ./common.yaml

volumes:
  vscode:
    name: vscode
  node:
    name: node
  dotnet:
    name: dotnet
  pwsh:
    name: pwsh
  docker:
    name: docker
  libicu:
    name: libicu
  yarn:
    name: yarn
