name: dev-env

services:
  vscode:
    image: gitpod/openvscode-server
    volumes:
      - vscode:/home/workspace
      - /home/${HOME}/.ssh:/home/openvscode-server/.ssh
      - /home/${HOME}:/home/${HOME}
      - donet:/usr/bin:ro
      - node:/usr/local/bin:ro
      - /var/run/docker.socket:/var/run/docker.socket:ro
    extends:
      service: common
      file: ./common.yaml

  node:
    image: node
    volumes:
      - node:/usr/local/bin:rw
    extends:
      service: common
      file: ./common.yaml

  donet:
    image: mcr.microsoft.com/dotnet/sdk
    volumes:
      - donet:/usr/bin:rw
    extends:
      service: common
      file: ./common.yaml

volumes:
  vscode:
    name: vscode
  node:
    name: node
  donet:
    name: donet
