name: dev-env

services:
  node:
    image: node
    entrypoint: /usr/bin/tail -f /dev/null
    volumes:
      - node:/usr/local/bin:rw
    extends:
      service: common
      file: ./common.yaml

  dotnet:
    image: mcr.microsoft.com/dotnet/sdk
    entrypoint: /usr/bin/tail -f /dev/null
    volumes:
      - dotnet:/usr/bin:rw
    extends:
      service: common
      file: ./common.yaml

  vscode:
    image: gitpod/openvscode-server
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/dotnet:/var/node
    volumes:
      - vscode:/home/workspace
      - /home/${HOME}/.ssh:/home/openvscode-server/.ssh
      - /home/${HOME}:/home/${HOME}
      - dotnet:/var/dotnet:ro
      - node:/vat/node:ro
      - /var/run/docker.socket:/var/run/docker.socket:ro
    extends:
      service: common
      file: ./common.yaml

volumes:
  vscode:
    name: vscode
  node:
    name: node
  dotnet:
    name: dotnet
