name: dev-env

services:
  vscode:
    image: gitpod/openvscode-server
    volumes:
      - vscode:/home/workspace
      - /home/${HOME}/.ssh:/home/openvscode-server/.ssh
      - /home/${HOME}:/home/${HOME}
      - usr:/usr/bin:ro
      - usrLocal:/usr/local/bin:ro
    extends:
      service: common
      file: ./common.yaml

  docker:
    image: docker
    volumes:
      - usrLocal:/usr/local/bin:rw
      - /var/run/docker.socket:/var/run/docker.socket:ro
    extends:
      service: common
      file: ./common.yaml

  node:
    image: node
    volumes:
      - usrLocal:/usr/local/bin:rw
    extends:
      service: common
      file: ./common.yaml

  donet:
    image: mcr.microsoft.com/dotnet/sdk
    volumes:
      - usr:/usr/bin:rw
    extends:
      service: common
      file: ./common.yaml

volumes:
  vscode:
    name: vscode
  usrLocal:
    name: usrLocal
  usr:
    name: usr
