name: dev-env

services:
  vscode:
    image: gitpod/openvscode-server
    volumes:
      - vscode:/home/workspace
      - /home/${HOME}/.ssh:/home/openvscode-server/.ssh
      - /home/${HOME}:/home/${HOME}
      - user:/usr/bin
      - usrLocal:/usr/local/bin
    extends:
      service: common
      file: ./common.yaml

  node:
    image: node
    volumes:
      - usrLocal:/usr/local/bin
    extends:
      service: common
      file: ./common.yaml

  donet:
    image: mcr.microsoft.com/dotnet/sdk
    volumes:
      - usr:/usr/bin
    extends:
      service: common
      file: ./common.yaml

  docker:
    image: docker
    volumes:
      - usrLocal:/usr/local/bin
    extends:
      service: common
      file: ./common.yaml

volumes:
  vscode:
    name: vscode
  usrLocal:
    name: docker
  usr:
    name: node
